### ISSUE TITLE
Tuya cl Curtain Switch (unsupported) da Tuya error and no command up/down/stop

### ISSUE THREAD

**Issue by MagicOneIta** [tuya/tuya-home-assistant#715]
### The problem

No work
![image](https://user-images.githubusercontent.com/20352749/143459899-b31f6a1f-a5e3-459c-a6c3-69cffcefd50e.png)

Device Information
Product Name Smart Curtain
Device ID 
Product Category cl
Device Status Online
Activated At 2020-05-06 18:20:15
Data Center Central Europe Data Center
Extension Information
Sub-Device or Not

### What version of Home Assistant Core has the issue?
2021.11.5

**Comment by EeeGee** [comment]
I have the same issue. Is there a solution?

**Comment by stevellion** [comment]
I have the same Issue

Some more info: - These are Quoya smart curtains (via Amazon) - they did previously work in older HA.

Product Name: 窗帘电动轨道
Product Category: cl

Json:
[
  {
    "code": "mach_operate",
    "value": "STOP"
  },
  {
    "code": "opposite",
    "value": true
  },
  {
    "code": "position",
    "value": 0
  }
]

Standard Instruction Set:
mach_operate | Enum | {   "range": [     "ZZ",     "FZ",     "STOP"   ] }
opposite | Boolean | "{true,false}"
position | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }

Standard Status Set:
opposite | Boolean | "{true,false}"
mach_operate | Enum | {   "range": [     "ZZ",     "FZ",     "STOP"   ] }
position | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }

**Comment by stevellion** [comment]
#652 Same Issue

**Comment by frenck** [comment]
Yesterday, Home Assistant 2022.2 was released.
Could you try upgrading to that version and see if the issue has been resolved?

If not, Home Assistant 2022.2 contains a new diagnostic tool. There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue. It will help with finding out what the problem is.

**Comment by MagicOneIta** [comment]
Yes the issue has been resolved! 
![bitmoji](https://sdk.bitmoji.com/render/panel/a3a7be99-7863-47f4-a180-3803b6b4c776-38a17c5b-3f7f-4529-806c-a34a1b5de7be-v1.png?transparent=1&palette=1&width=246)
